import '../node_modules/basiclightbox/dist/basicLightbox.min.css';
import './js/moviebyGenre';
import './js/initPage';
import './js/modalCard';
import './js/renderModal';
import './js/searchInput';
import './js/team-modal';
import './js/videotube';
// import './js/themeColor';
// import './js/storageThemeColor';
import './js/scroll-up-btn';
