import '../node_modules/basiclightbox/dist/basicLightbox.min.css';
import './js/filter';
import './js/initPage';
import './js/modalCard';
import './js/renderModal';
// import './js/colorButton';
import './js/searchInput';
import './js/team-modal';
// import './js/themeColor';
// import './js/storageThemeColor';
import './js/scroll-up-btn';
